name: AWS Lambda Deployment

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy to AWS Lambda
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install serverless framework
        run: npm install -g serverless

      - name: Install serverless-offline plugin
        run: npm install --save-dev serverless-offline

      - name: Deploy to AWS Lambda
        run: |
          serverless config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          serverless deploy


name: Bizcard AI API - Dev
on:
  push:
    branches:
      - dev
jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    environment: 
      name: dev
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - run: aws s3 cp s3://bizcard-environment/configs/config.dev.json config/
      - run: npm cache clean --force
      - run: sudo npm install -g n
      - run: sudo n 18.17.0
      - run: npm i -g serverless
      - run: npm i
      - run: cp ./serverless/dev-serverless.yml serverless.yml
      - run: ls
      - run: serverless package
      - run: ls
      - run: serverless deploy --stage dev --region ${{ secrets.AWS_DEFAULT_REGION }}

